baseURL = "http://aws-samples.github.io/debug-k8s-apps/"
languageCode = "en-us"
publishDir = "docs"
disableKinds = ["sitemap", "RSS", "taxonomyTerm"]
title = "debug-k8s-apps"
theme = "reveal-hugo"

[params.reveal_hugo]
slide_number = true
control = false

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
