baseURL = "http://aws-samples.github.io/debug-k8s-apps/"
languageCode = "en-us"
publishDir = "docs"
disableKinds = ["sitemap", "RSS"]
title = "My New Hugo Site"
theme = "reveal-hugo"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
